### ISSUE TITLE
Plugin doesn't work as expected

### ISSUE THREAD

**Issue by JustFly1984** [fenok/extract-hoc-compose#1]
I use `react-static` tool for bundling my react app. It uses the same HMR settings as create-react-app.
It allows to modify webpack config.

My webpack dev config rules looks like this:
```
[
      eslintRule,
      {
        oneOf: [
          defaultLoaders.jsLoader,
          loadCSSwithoutModulesRule,
          loadCSSModulesDevRule,
          defaultLoaders.fileLoader
        ]
      }
    ]
```
The issue is that I have a lot of HOCs and composed HOCs too, so my HMR goes to infinite recursive loop and hangs on save.

I added your rule, a bit modified it, cos I got JSX errors

```
[
      eslintRule,
      {
         test: /\.js$/,
  use: [
    {
      loader: require.resolve('babel-loader')
    },
    {
      loader: require.resolve('babel-loader'),
      options: {
        plugins: ['extract-hoc-compose/babel', 'extract-hoc/babel'],
        presets: ['react', 'react-app'],
        babelrc: false
      }
    }
  ],
  exclude: [/node_modules/]
},
      {
        oneOf: [
          defaultLoaders.jsLoader,
          loadCSSwithoutModulesRule,
          loadCSSModulesDevRule,
          defaultLoaders.fileLoader
        ]
      }
    ]
``` 

But I still get ton of warnings:
<img width="1379" alt="screenshot 2018-02-05 13 37 45" src="https://user-images.githubusercontent.com/2255993/35789815-cb821192-0a79-11e8-9f60-407e0c877a7b.png">

Related to withRouter, InjectIntl, Connect, recompose.

Should I use your plugin together with `extract-hoc` or you plugin replacing it?

**Comment by fenok** [comment]
This plugin is designed to handle one specific syntax, as described in readme. Anyway, you should use [react-hot-loader v4 (beta)](https://github.com/gaearon/react-hot-loader/tree/next), wich solves issues with HOCs in a general way. You don't need extract-hoc and/or extract-hoc-compose to use it. Hope it will help you just as it helped me. Cheers.

**Comment by JustFly1984** [comment]
Thank you, but I have no control on react-hot-loader version, as it comes
as dependencie of my build toolchain - which is create-react-app or
react-static

2018-02-07 3:36 GMT+08:00 Leonid Fenko <notifications@github.com>:
